#!/bin/bash
find -mindepth 1 -type d | wc -l
#!/bin/bash
count=0
for file in ./*/
do
 if [[ "" != "./" && "" != "../" ]]
    then
        (( count++ ))
    fi
done
if [[ "" != "./." && "" != "./.." ]]
    then
        (( count++ ))
    fi
done
